name: MSBuild

on:
  push:
    branches: [ "v4-patch" ]
  pull_request:
    branches: [ "v4-patch" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: node.vcxproj
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'v4-patch'
    
    - name: Install build tools 2015
      shell: powershell
      run: |
        Start-Process -Wait "%programfiles(x86)%\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList "modify", "--installPath", "%programfiles(x86)%\Microsoft Visual Studio 2022", "--add", "Microsoft.VisualStudio.Component.VC.140", "-q"


    - name: Install Windows 8.1 SDK
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup Python version
      uses: actions/setup-python@v4
      with:
        python-version: '2.7'

    - name: Build NodeJS
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:PlatformToolSet="v140" ${{env.SOLUTION_FILE_PATH}}