name: MSBuild

on:
  push:
    branches: [ "v4-patch" ]
  pull_request:
    branches: [ "v4-patch" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: node.vcxproj
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'v4-patch'

    - name: Install Windows 8.1 SDK
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup Python version
      uses: actions/setup-python@v4
      with:
        python-version: '2.7.18'

    - name: Build NodeJS
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:PlatformToolSet="v140" ${{env.SOLUTION_FILE_PATH}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nodejs-artifacts
        path: |
          build/
          src/
          deps/uv/include/
          deps/v8/include/
          deps/openssl/openssl/include/
