name: MSBuild

on:
  push:
    branches: [ "v4-patch" ]
  pull_request:
    branches: [ "v4-patch" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: node.vcxproj
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'v4-patch'

    - name: Download SDK for Windows 8.1
      uses: suisei-cn/actions-download-file@v1.3.0
      id: downloadfile
      with:
        url: "https://go.microsoft.com/fwlink/p/?LinkId=323507"
        target: sdk/
        filename: sdksetup.exe
    
    - name: Install SDK for Windows 8.1
      run: sdk/sdksetup.exe /features + /q

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      # with:
      #   vs-version: '14.0'
    
    - name: Setup Python version
      uses: actions/setup-python@v4
      with:
        python-version: '2.7'

    - name: Build NodeJS
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:PlatformToolSet="v140" ${{env.SOLUTION_FILE_PATH}}